modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Etyl/ImmersiveFarming/issues"

[[mods]]
modId="immersivefarming"
version="${file.jarVersion}"
displayName="Immersive Farming"
logoFile="logo.png"
authors="Etyl"
description="Addon for Immersive Engineering focusing on improving the farming experience."

[[dependencies.immersivefarming]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.18.2-8.4.0-161,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.immersivefarming]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersivefarming]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"